### ISSUE TITLE
RuntimeError: coroutine raised StopIteration

### ISSUE THREAD

**Issue by Jasperb3** [Hellisotherpeople/llm_steer-oobabooga#1] opened 2024-03-21 10:42 UTC
This extension looks very interesting but when trying to add a steering vector, I get this error. Any ideas how to solve it?

Traceback (most recent call last):
  File "C:\Users\XYZ\miniconda3\envs\textgen\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XYZ\miniconda3\envs\textgen\Lib\site-packages\gradio\utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\XYZ\text-generation-webui\extensions\llm_steer-oobabooga\script.py", line 157, in add_steering_vector
    shared.steered_model = Steer(shared.model, shared.tokenizer)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XYZ\miniconda3\envs\textgen\Lib\site-packages\llm_steer.py", line 41, in __init__
    self.device = torch.device(next(model.parameters()).device)
                               ^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\XYZ\miniconda3\envs\textgen\Lib\site-packages\gradio\queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XYZ\miniconda3\envs\textgen\Lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XYZ\miniconda3\envs\textgen\Lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XYZ\miniconda3\envs\textgen\Lib\site-packages\gradio\blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XYZ\miniconda3\envs\textgen\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XYZ\miniconda3\envs\textgen\Lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
RuntimeError: coroutine raised StopIteration

**Comment by Hellisotherpeople** [comment] 2024-03-21 13:05
Hi, not exactly sure what the issue is here. This extension only works for the transformers backend. Can you confirm that you are using the transformers backend?

What model are you trying to run?

**Comment by Jasperb3** [comment] 2024-03-21 13:37
Hi, thanks for your reply.

I was trying it with an EXL2 model (bartowski_dolphin-2.8-experiment26-7b-exl2_8_0) with the ExLlamav2_HF loader.

Might be worth adding to the readme if it only works with transformers.

**Comment by Hellisotherpeople** [comment] 2024-03-21 13:39
Yes, I will add it. Apologies for the confusion. 

I would suggest writing an issue asking for support for other backends in llm_steer: https://github.com/Mihaiii/llm_steer

**Comment by Hellisotherpeople** [comment] 2024-03-21 20:04
I will close this as I am at the whims of llm_steer for supporting other backends - but I will ask Mihaiii to

**Closed as completed by Hellisotherpeople** 2024-03-21 20:04 UTC

**Comment by marknasr22** [comment] 2024-11-11 11:38
Any news? Same issue with llamacpp_HF. I thought HF loads as Transformers?
